apiVersion: v1
kind: Pod
metadata:
  name: pod-red
  namespace: production
  labels:
    app: web
spec:
  containers:
  - name: webapp-red
    image: mmumshad/simple-webapp-color
    env:
    - name: COLOR
      value: red
    ports:
    - containerPort: 80:80     