apiVersion: v1
kind: Pod
metadata:
  name: pod-blue
  namespace: production
  labels:
    app: web
spec:
  containers:
  - name: webapp-blue
    image: mmumshad/simple-webapp-color
    env:
    - name: COLOR
      value: blue
    ports:
    - containerPort: 8080     