
apiVersion: v1
kind: Pod
metadata:
  name: webapp-red
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: mmumshad/simple-webapp-color
    ports:
    - containerPort: 8080
    env:
    - name: APP_COLOR
      value: "red" 
